### PR TITLE
New Themes for Sanny Builder

### PR DESCRIPTION
**Pull request by ghost**
Added images of NeoDark theme and SB Library Dark theme, and added SB Library Dark Theme.

### CODE REVIEW

**Comment by x87** [comment]
@johnnie-br thank you for your contribution. Would you be able to adapt these themes to Sanny Builder 4? There are extra colors for tabs

**Comment by ghost** [comment]
@x87 
> @johnnie-br thank you for your contribution. Would you be able to adapt these themes to Sanny Builder 4? There are extra colors for tabs

Sure, Just one question, will the new themes work for the old version? If not, I can create a division for themes before 4.0 and themes after 4.0

**Comment by x87** [comment]
> Sure, Just one question, will the new themes work for the old version? If not, I can create a division for themes before 4.0 and themes after 4.0

yes, old version will ignore new properties

**Comment by ghost** [comment]
@x87 Should I adapt everyone including others or just mine?

**Comment by x87** [comment]
just yours

**Pull request closed without merging**
